# Generated by Django 3.2.9 on 2021-12-18 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('job_number', models.PositiveBigIntegerField(verbose_name=django.core.validators.MaxValueValidator(999999, 'Invalid Job Number'))),
                ('display_name', models.CharField(default=models.CharField(max_length=120), max_length=120)),
            ],
        ),
    ]
