# Generated by Django 3.2.9 on 2021-12-18 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='job_number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999, 'Invalid Job Number')]),
        ),
    ]
