# Generated by Django 3.2.9 on 2021-12-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_name',
            field=models.CharField(max_length=120),
        ),
    ]
