# Generated by Django 3.2.9 on 2021-12-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_scope_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.scope'),
        ),
    ]
