# Generated by Django 3.2.9 on 2021-12-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_scope_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='scope',
            name='parent_scope',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.scope'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
