# Generated by Django 3.2.9 on 2021-12-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20211221_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='parent_scope',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.scope'),
        ),
    ]
