# Generated by Django 3.2.9 on 2022-10-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_steelgrade_steeltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='steelsectiontype',
            name='preferred_steel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calc.steelgrade'),
            preserve_default=False,
        ),
    ]
