# Generated by Django 3.2.9 on 2022-10-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_steelsectiontype_preferred_steel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steeltype',
            old_name='type',
            new_name='name',
        ),
    ]
