# Generated by Django 3.2.9 on 2022-10-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rename_type_steeltype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steelsectiontype',
            old_name='type',
            new_name='name',
        ),
    ]
