# Generated by Django 3.2.9 on 2022-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_rename_type_steelsectiontype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='steelgrade',
            name='E',
            field=models.IntegerField(default=29000),
            preserve_default=False,
        ),
    ]
