# Generated by Django 3.2.9 on 2022-12-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_aisc360version_asce7version_designmethod_loadcombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcombination',
            name='num',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
